### ISSUE TITLE
[android] EnableTurnNotifications(): CHECK(m_threadChecker.CalledOnOriginalThread())

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#6903]
Have 2 logs from Android users like this:

```
12-19 10:20:00.791  9658  9688 W TextToSpeech: System TTS connection error: Failed creating TTS session: java.lang.IllegalStateException: Failed to bind to service Intent { act=android.intent.action.TTS_SERVICE pkg=com.google.android.tts }
12-19 10:20:00.791  9658  9688 E TtsPlayer: TtsPlayer.java:148 lambda$initialize$0(): Failed to initialize TextToSpeach
12-19 10:20:00.791  9658  9688 E OMcore  : routing/routing_session.cpp:722 EnableTurnNotifications(): CHECK(m_threadChecker.CalledOnOriginalThread()) 
```

```
 LineageOS Version: '20.0-20231127-RELEASE-thyme'
 Build fingerprint: 'Xiaomi/thyme/thyme:12/SKQ1.211006.001/V13.0.8.0.SGACNXM:user/release-keys'
 Revision: '0'
 ABI: 'arm64'
 Timestamp: 2023-12-19 07:53:11.946313360+0800
 Process uptime: 1s
 Cmdline: app.organicmaps
 pid: 25487, tid: 25499, name: binder:25487_1  >>> app.organicmaps <<<
 uid: 10226
 signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
     x0  0000000000000000  x1  000000000000639b  x2  0000000000000006  x3  00000076a07238b0
     x4  1f313136396f6f62  x5  1f313136396f6f62  x6  1f313136396f6f62  x7  7f7f7f7f7f7f7f7f
     x8  00000000000000f0  x9  00000079a9f239e0  x10 0000000000000001  x11 00000079a9f65360
     x12 00000000000060ca  x13 000000000000006c  x14 b400007784dc03b0  x15 00000000341555ac
     x16 00000079a9fd1d50  x17 00000079a9fade70  x18 000000769fb88000  x19 000000000000638f
     x20 000000000000639b  x21 00000000ffffffff  x22 00000076a0725000  x23 0000000000000000
     x24 0000000000000000  x25 00000076a0723ac0  x26 00000076a0723ac4  x27 00000076a0723ac0
     x28 00000076a0723ad0  x29 00000076a0723930
     lr  00000079a9f551b8  sp  00000076a0723890  pc  00000079a9f551e4  pst 0000000000001000
 backtrace:
       #00 pc 00000000000531e4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 9298be534abc53e2b055c7caf3d3e48a)
       #01 pc 000000000098ebd4  /data/app/~~gISpIYDPJwMwbof2At-o1g==/app.organicmaps-2qppZqfACc9lWOtfSKP5nA==/split_config.arm64_v8a.apk!liborganicmaps.so (offset 0x1000) (routing::RoutingSession::EnableTurnNotifications(bool)+292) (BuildId: 9a0cfb5e1abb4f078f4123f6d7de6bd4f1def37b)
       #02 pc 000000000001d1d4  /data/app/~~gISpIYDPJwMwbof2At-o1g==/app.organicmaps-2qppZqfACc9lWOtfSKP5nA==/oat/arm64/base.odex (art_jni_trampoline+116)
       #03 pc 0000000000209398  /apex/com.android.art/lib64/libart.so (nterp_helper+152) (BuildId: 0d5226ac1e0dd54e7f5c7afd22fa1439)
       #04 pc 00000000002076fa  /data/app/~~gISpIYDPJwMwbof2At-o1g==/app.organicmaps-2qppZqfACc9lWOtfSKP5nA==/oat/arm64/base.vdex (app.organicmaps.sound.TtsPlayer.setEnabled+6)
       #05 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 0d5226ac1e0dd54e7f5c7afd22fa1439)
       #06 pc 00000000002076a4  /data/app/~~gISpIYDPJwMwbof2At-o1g==/app.organicmaps-2qppZqfACc9lWOtfSKP5nA==/oat/arm64/base.vdex (app.organicmaps.sound.TtsPlayer.lockDown+8)
       #07 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 0d5226ac1e0dd54e7f5c7afd22fa1439)
       #08 pc 0000000000207622  /data/app/~~gISpIYDPJwMwbof2At-o1g==/app.organicmaps-2qppZqfACc9lWOtfSKP5nA==/oat/arm64/base.vdex (app.organicmaps.sound.TtsPlayer.lambda$initialize$0+22)
       #09 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 0d5226ac1e0dd54e7f5c7afd22fa1439)
       #10 pc 0000000000207510  /data/app/~~gISpIYDPJwMwbof2At-o1g==/app.organicmaps-2qppZqfACc9lWOtfSKP5nA==/oat/arm64/base.vdex (app.organicmaps.sound.TtsPlayer.$r8$lambda$3SSSSkazhW4Oul7qbLqitq6zxBw+0)
       #11 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 0d5226ac1e0dd54e7f5c7afd22fa1439)
       #12 pc 000000000020707c  /data/app/~~gISpIYDPJwMwbof2At-o1g==/app.organicmaps-2qppZqfACc9lWOtfSKP5nA==/oat/arm64/base.vdex (app.organicmaps.sound.TtsPlayer$$ExternalSyntheticLambda1.onInit+8)
       #13 pc 000000000020b074  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 0d5226ac1e0dd54e7f5c7afd22fa1439)
       #14 pc 000000000023ebb6  /system/framework/framework.jar (android.speech.tts.TextToSpeech.lambda$dispatchOnInit$0$android-speech-tts-TextToSpeech+14)
       #15 pc 000000000059b3fc  /system/framework/arm64/boot-framework.oat (android.speech.tts.TextToSpeech.dispatchOnInit+172) (BuildId: ec3390b3657c47ec85baf31a01b67ad22aa293c6)
       #16 pc 000000000020a2b0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016) (BuildId: 0d5226ac1e0dd54e7f5c7afd22fa1439)
       #17 pc 000000000023e9ac  /system/framework/framework.jar (android.speech.tts.TextToSpeech.-$$Nest$mdispatchOnInit+0)
       #18 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 0d5226ac1e0dd54e7f5c7afd22fa1439)
       #19 pc 000000000023ac96  /system/framework/framework.jar (android.speech.tts.TextToSpeech$SystemConnection$1.onError+58)
       #20 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 0d5226ac1e0dd54e7f5c7afd22fa1439)
       #21 pc 0000000000239104  /system/framework/framework.jar (android.speech.tts.ITextToSpeechSessionCallback$Stub.onTransact+72)
       #22 pc 00000000005435b8  /system/framework/arm64/boot-framework.oat (android.os.Binder.execTransactInternal+952) (BuildId: ec3390b3657c47ec85baf31a01b67ad22aa293c6)
       #23 pc 00000000005430e0  /system/framework/arm64/boot-framework.oat (android.os.Binder.execTransact+304) (BuildId: ec3390b3657c47ec85baf31a01b67ad22aa293c6)
       #24 pc 000000000021096c  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+556) (BuildId: 0d5226ac1e0dd54e7f5c7afd22fa1439)
       #25 pc 0000000000279de8  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+184) (BuildId: 0d5226ac1e0dd54e7f5c7afd22fa1439)
       #26 pc 0000000000622bc4  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+468) (BuildId: 0d5226ac1e0dd54e7f5c7afd22fa1439)
       #27 pc 0000000000622e3c  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92) (BuildId: 0d5226ac1e0dd54e7f5c7afd22fa1439)
       #28 pc 0000000000479e0c  /apex/com.android.art/lib64/libart.so (art::JNI<false>::CallBooleanMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+652) (BuildId: 0d5226ac1e0dd54e7f5c7afd22fa1439)
       #29 pc 00000000000c07b8  /system/lib64/libandroid_runtime.so (_JNIEnv::CallBooleanMethod(_jobject*, _jmethodID*, ...)+120) (BuildId: 3bf516fc17563831b9c9eb0037fc154e)
       #30 pc 000000000017238c  /system/lib64/libandroid_runtime.so (JavaBBinder::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+156) (BuildId: 3bf516fc17563831b9c9eb0037fc154e)
       #31 pc 000000000005213c  /system/lib64/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+236) (BuildId: 3ba5cc39f742fe029794739ff4874e3b)
       #32 pc 000000000005d994  /system/lib64/libbinder.so (android::IPCThreadState::executeCommand(int)+1012) (BuildId: 3ba5cc39f742fe029794739ff4874e3b)
       #33 pc 000000000005d4d0  /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+160) (BuildId: 3ba5cc39f742fe029794739ff4874e3b)
       #34 pc 000000000005dd64  /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+68) (BuildId: 3ba5cc39f742fe029794739ff4874e3b)
       #35 pc 000000000008dba8  /system/lib64/libbinder.so (android::PoolThread::threadLoop()+24) (BuildId: 3ba5cc39f742fe029794739ff4874e3b)
       #36 pc 0000000000013440  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+416) (BuildId: 10aac5d4a671e4110bc00c9b69d83d8a)
       #37 pc 00000000000c8f6c  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+140) (BuildId: 3bf516fc17563831b9c9eb0037fc154e)
       #38 pc 00000000000c222c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: 9298be534abc53e2b055c7caf3d3e48a)
       #39 pc 0000000000054a20  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 9298be534abc53e2b055c7caf3d3e48a)
```
